In [1]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [2]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [3]:
downloaded = drive.CreateFile({'id':'1fXIBpCkjR855HCRjEa7_BDuwZsj05Vwg'}) # replace the id with id of file you want to access
downloaded.GetContentFile('Cosmetic shop.csv')

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mpl_toolkits
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import datetime as dt
%matplotlib inline
dataset=pd.read_csv("Cosmetic shop.csv")
dataset

    ID    Age  Income  Gender Marital Status Buys
0    1    <21    High    Male         Single   No
1    2    <21    High    Male        Married   No
2    3  21-35    High    Male         Single  Yes
3    4    >35  Medium    Male         Single  Yes
4    5    >35     Low  Female         Single  Yes
5    6    >35     Low  Female        Married   No
6    7  21-35     Low  Female        Married  Yes
7    8    <21  Medium    Male         Single   No
8    9    <21     Low  Female        Married  Yes
9   10    >35  Medium  Female         Single  Yes
10  11    <21  Medium  Female        Married  Yes
11  12  21-35  Medium    Male        Married  Yes
12  13  21-35    High  Female         Single  Yes
13  14    >35  Medium    Male        Married   No

In [5]:
X=dataset.iloc[:,:-1]
X

    ID    Age  Income  Gender Marital Status
0    1    <21    High    Male         Single
1    2    <21    High    Male        Married
2    3  21-35    High    Male         Single
3    4    >35  Medium    Male         Single
4    5    >35     Low  Female         Single
5    6    >35     Low  Female        Married
6    7  21-35     Low  Female        Married
7    8    <21  Medium    Male         Single
8    9    <21     Low  Female        Married
9   10    >35  Medium  Female         Single
10  11    <21  Medium  Female        Married
11  12  21-35  Medium    Male        Married
12  13  21-35    High  Female         Single
13  14    >35  Medium    Male        Married

In [6]:
y=dataset.iloc[:,5]
y

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Buys, dtype: object

In [7]:
#perform label encoding to convert categorical data into numerical data
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()#we have created the object of label encoder

In [8]:
X=X.apply(LabelEncoder().fit_transform) # we provided input as 'x' values to the label encoder
print(X)

    ID  Age  Income  Gender  Marital Status
0    0    1       0       1               1
1    1    1       0       1               0
2    2    0       0       1               1
3    3    2       2       1               1
4    4    2       1       0               1
5    5    2       1       0               0
6    6    0       1       0               0
7    7    1       2       1               1
8    8    1       1       0               0
9    9    2       2       0               1
10  10    1       2       0               0
11  11    0       2       1               0
12  12    0       0       0               1
13  13    2       2       1               0

In [9]:
from sklearn.tree import DecisionTreeClassifier
regressor=DecisionTreeClassifier()
regressor.fit(X.iloc[:,1:5],y)

DecisionTreeClassifier()

In [10]:
#predict value for the given Expression
x_in=np.array([1,1,0,0])
y_pred=regressor.predict([x_in])
print("Prediction:",y_pred)

Prediction: ['Yes']

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [11]:
#sys.modules['sklearn.externals.six']=six
from six import StringIO
#from sys.modules['sklearn.externals.six'] import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus

In [12]:
dot_data=StringIO()
export_graphviz(regressor,out_file=dot_data,filled=True,rounded=True,special_characters=True)
graph=pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png("tree.png")

True